config/routes.rb
Chaskiq::Engine.routes.draw do

  root 'dashboard#show'

  resource :oembed, controller: "oembed", only: :show

  #public
  resources :campaigns, only: :show do
    member do
      get :subscribe
      get :unsubscribe
      get :forward
    end

    resources :subscribers do
      member do
        get :delete
      end
    end

    resources :tracks do
      member do
        get :click
        get :open
        get :bounce
        get :spam
      end
    end
  end

  #private
  scope 'manage',as: :manage do
    resources :campaigns, controller: 'manage/campaigns' do
      resources :wizard, controller: 'manage/campaign_wizard'
      member do
        get :preview
        get :premailer_preview
        get :test
        get :deliver
        get :clone
        get :editor
        get :purge
        get :iframe
      end
      resources :attachments, controller: 'manage/attachments'
      resources :metrics, controller: 'manage/metrics'
    end

    resources :lists, controller: 'manage/lists' do
      member do
        patch :upload
        get :clear
      end
      resources :subscribers, controller: 'manage/subscribers'
    end
    resources :templates, controller: 'manage/templates'
  end

  resources :hooks do
    collection do
    end
  end

end

app/models/chaskiq/attachment.rb
module Chaskiq
  class Attachment < ActiveRecord::Base
    belongs_to :campaign, optional: true

    mount_uploader :image, ImageUploader

  end
end

app/models/chaskiq/campaign.rb
require 'net/http'
require 'open-uri'

module Chaskiq
  class Campaign < ActiveRecord::Base

    belongs_to :parent, class_name: "Chaskiq::Campaign", optional: true
    belongs_to :list
    has_many :subscribers, through: :list
    has_many :subscriptions, through: :subscribers
    has_many :attachments
    has_many :metrics
    belongs_to :template, class_name: "Chaskiq::Template", optional: true
    #accepts_nested_attributes_for :template, :campaign_template

    attr_accessor :step

    validates :subject, presence: true , unless: :step_1?
    validates :from_name, presence: true, unless: :step_1?
    validates :from_email, presence: true, unless: :step_1?

    #validates :plain_content, presence: true, unless: :template_step?
    validates :html_content, presence: true, if: :template_step?

    before_save :detect_changed_template

    mount_uploader :logo, CampaignLogoUploader

    def delivery_progress
      return 0 if metrics.deliveries.size.zero?
      subscriptions.availables.size.to_f / metrics.deliveries.size.to_f * 100.0
    end

    def subscriber_status_for(subscriber)
      #binding.pry
    end

    def step_1?
      self.step == 1
    end

    def template_step?
      self.step == "template"
    end

    def purge_metrics
      self.metrics.delete_all
    end

    def send_newsletter
      Chaskiq::MailSenderJob.perform_later(self)
    end

    def test_newsletter
      Chaskiq::CampaignMailer.test(self).deliver_later
    end

    def clone_newsletter
      cloned_record = self.deep_clone #(:include => :subscribers)
      cloned_record.name = self.name + "-copy"
      cloned_record
    end

    def detect_changed_template
      if self.changes.include?("template_id")
        copy_template
      end
    end

    #deliver email + create metric
    def push_notification(subscription)
      Chaskiq::SesSenderJob.perform_later(self, subscription)
    end

    def prepare_mail_to(subscription)
      Chaskiq::CampaignMailer.newsletter(self, subscription)
    end

    def copy_template
      self.html_content    = self.template.body
      self.html_serialized = self.template.body
      self.css = self.template.css
    end

    def campaign_url
      host = Rails.application.routes.default_url_options[:host]
      campaign_url = "#{host}/campaigns/#{self.id}"
    end

    def apply_premailer(opts={})
      host = Rails.application.routes.default_url_options[:host]
      skip_track_image = opts[:exclude_gif] ? "exclude_gif=true" : nil
      premailer_url = ["#{host}/manage/campaigns/#{self.id}/premailer_preview", skip_track_image].join("?")
      url = URI.parse(premailer_url)
      self.update_column(:premailer, clean_inline_css(url))
    end

    #will remove content blocks text
    def clean_inline_css(url)
      
      html = open(url).readlines.join("")
      #document = Roadie::Document.new html
      #document.transform

      premailer = Premailer.new(url, :adapter => :nokogiri, :escape_url_attributes => false)
      premailer.to_inline_css
    end

    def attributes_for_mailer(subscriber)

      subscriber_url = "#{campaign_url}/subscribers/#{subscriber.encoded_id}"
      track_image    = "#{campaign_url}/tracks/#{subscriber.encoded_id}/open.gif"

      { campaign_url: campaign_url,
        campaign_unsubscribe: "#{subscriber_url}/delete",
        campaign_subscribe: "#{campaign_url}/subscribers/new",
        campaign_description: "#{self.description}",
        track_image_url: track_image
      }
    end

    def mustache_template_for(subscriber)

      link_prefix = host + "/campaigns/#{self.id}/tracks/#{subscriber.encoded_id}/click?r="

      #html = Chaskiq::LinkRenamer.convert(premailer, link_prefix)
      subscriber_options = subscriber.attributes
                                      .merge(attributes_for_mailer(subscriber))
                                      .merge(subscriber.options)
                             
      compiled_premailer = premailer.gsub("%7B%7B", "{{").gsub("%7D%7D", "}}")                               
      compiled_mustache = Mustache.render(compiled_premailer, subscriber_options)

      html = Chaskiq::LinkRenamer.convert(compiled_mustache, link_prefix)
      html
    end

    def compiled_template_for(subscriber)
      html = mustache_template_for(subscriber)
    end

    def host
      Rails.application.routes.default_url_options[:host] || "http://localhost:3000"
    end

    ## CHART STUFF
    def sparklines_by_day(opts={})
      range = opts[:range] ||= 2.weeks.ago.midnight..Time.now
      self.metrics.group_by_day(:created_at, range: range ).count.map{|o| o.to_a.last}
    end

  end
end

app/models/chaskiq/list.rb
module Chaskiq
  class List < ActiveRecord::Base
    has_many :subscriptions #, dependent: :destroy
    has_many :subscribers, through: :subscriptions
    has_many :campaigns

    accepts_nested_attributes_for :subscribers
    
    attr_accessor :upload_file

    def subscription_progress
      return 0 if subscribers.where(state: "subscribed").size.zero?
      (subscribers.where(state: "subscribed").size.to_f / subscribers.size.to_f  * 100.0).to_i
    end

    def import_csv(file)
      ListImporter.import(file, params: {list_id: self.id})
    end

    def create_subscriber(subscriber)
      sub = self.subscribers.find_or_initialize_by(email: subscriber[:email])
      sub.name = subscriber[:name]
      sub.last_name = subscriber[:last_name]
      s = self.subscriptions.find_or_initialize_by(id: sub.id)
      s.subscriber = sub
      s.save
      s.subscriber
    end

    def unsubscribe(subscriber)
      s = subscriptions.find_by(subscriber: subscriber)
      s.unsubscribe!
    end

    def subscribe(subscriber)
      s = subscriptions.find_by(subscriber: subscriber)
      s.subscribe!
    end

    def csv_importer
      @importer ||= Chaskiq::CsvImporter.new
    end

  end
end

app/models/chaskiq/metric.rb
module Chaskiq
  class Metric < ActiveRecord::Base
    belongs_to :campaign
    belongs_to :trackable, polymorphic: true, required: true
    #belongs_to :subscription, ->{ where("chaskiq_metrics.trackable_type =?", "Chaskiq::Subscription")}, foreign_key: :trackable_id
    belongs_to :subscription, foreign_key: :trackable_id

    #system output
    scope :deliveries, ->{where(action: "deliver")}

    #user feedback
    scope :bounces, ->{ where(action: "bounce")}
    scope :opens,   ->{ where(action: "open") }
    scope :clicks,  ->{ where(action: "click")}
    scope :spams,   ->{ where(action: "spam") }

    #reportery
    scope :uniques, ->{group("host")}

  end
end

app/models/chaskiq/setting.rb
module Chaskiq
  class Setting < ActiveRecord::Base
    belongs_to :campaign
  end
end

app/controllers/chaskiq/application_controller.rb
require "wicked"

module Chaskiq
  class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    
    def get_referrer
      ip = request.remote_ip
    end

    def authentication_method
      if meth = Chaskiq::Config.authentication_method
        self.send meth
      end
    end

    def cors_set_access_control_headers
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
      headers['Access-Control-Max-Age'] = "1728000"
    end

    def cors_preflight_check
      if request.method == 'OPTIONS'
        headers['Access-Control-Allow-Origin'] = '*'
        headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
        headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
        headers['Access-Control-Max-Age'] = '1728000'

        render :text => '', :content_type => 'text/plain'
      end
    end
    

  end
end

app/controllers/chaskiq/campaigns_controller.rb
require_dependency "chaskiq/application_controller"

module Chaskiq
  class CampaignsController < ApplicationController

    layout "chaskiq/empty"

    before_action :find_campaign

    def show
    end

    def find_campaign
      @campaign = Chaskiq::Campaign.find(params[:id])
    end
  end
end

app/controllers/chaskiq/dashboard_controller.rb
require_dependency "chaskiq/application_controller"

module Chaskiq
  class DashboardController < Chaskiq::ApplicationController
    before_action :authentication_method

    def show
      @campaigns_count = Chaskiq::Campaign.count
      @sends_count     = Chaskiq::Metric.deliveries.size
      @daily_metrics   = Chaskiq::Metric.group_by_day(:created_at, range: 2.weeks.ago.midnight..Time.now).count
      @pie_metrics     = Chaskiq::Metric.group(:action)
      @campaigns       = Chaskiq::Campaign.order("updated_at desc").page(1).per(10)
    
      range = 2.weeks.ago.midnight..Time.now

      @chart_data = [
        {name: :opens,   color: "blue", data: Chaskiq::Metric.opens.group_by_day(:created_at, range: range).count},
        {name: :clicks,  color: "green", data: Chaskiq::Metric.clicks.group_by_day(:created_at, range: range).count},
        {name: :bounces, color: "yellow", data: Chaskiq::Metric.bounces.group_by_day(:created_at, range: range).count},
        {name: :spams,   color: "red", data: Chaskiq::Metric.spams.group_by_day(:created_at, range: range).count}
      ]

    end
  end
end

app/controllers/chaskiq/hooks_controller.rb
require_dependency "chaskiq/application_controller"

require "open-uri"
module Chaskiq
  class HooksController < ApplicationController

    layout false

    def create
      # get amazon message type and topic
      amz_message_type = request.headers['x-amz-sns-message-type']
      amz_sns_topic = request.headers['x-amz-sns-topic-arn']

      #return unless !amz_sns_topic.nil? &&
      #amz_sns_topic.to_s.downcase == 'arn:aws:sns:us-west-2:867544872691:User_Data_Updates'
      request_body = JSON.parse request.body.read

      # if this is the first time confirmation of subscription, then confirm it
      if amz_message_type.to_s.downcase == 'subscriptionconfirmation'
        send_subscription_confirmation request_body
        render plain: "ok" and return
      end

      process_notification(request_body)
      render plain: "ok" and return
    end

private

    def process_notification(request_body)

      message = parse_body_message(request_body["Message"])

      case message["notificationType"]
      when "Bounce"
        process_bounce(message)
      when "Complaint"
        process_complaint(message)
      end
    end

    def parse_body_message(body)
      JSON.parse(body)
    end

    def process_bounce(m)
      emails = m["bounce"]["bouncedRecipients"].map{|o| o["emailAddress"] }
      source = m["mail"]["source"]
      track_message_for("bounce", m)
    end

    def process_complaint(m)
      emails = m["complaint"]["complainedRecipients"].map{|o| o["emailAddress"] }
      source = m["mail"]["source"]
      track_message_for("spam", m)
    end

    def track_message_for(track_type, m)
      Chaskiq::SnsReceiverJob.perform_later(track_type, m, get_referrer)
    end

    def send_subscription_confirmation(request_body)
      subscribe_url = request_body['SubscribeURL']
      return nil unless !subscribe_url.to_s.empty? && !subscribe_url.nil?
      subscribe_confirm = open subscribe_url
    end

  end
end

app/controllers/chaskiq/lists_controller.rb
require_dependency "chaskiq/application_controller"

module Chaskiq
  class ListsController < ApplicationController

  protected

  end
end

app/controllers/chaskiq/oembed_controller.rb
require_dependency "chaskiq/application_controller"

module Chaskiq
  class OembedController < ApplicationController
  
    before_action :cors_preflight_check
    after_action :cors_set_access_control_headers
    
    def show
      res = FetchLinkCardService.new.call(params[:url])
      render json: res.as_oembed_json
    end


  end
end

app/controllers/chaskiq/subscribers_controller.rb
require_dependency "chaskiq/application_controller"

module Chaskiq
  class SubscribersController < ApplicationController

    before_action :find_base_models

    layout "chaskiq/empty"

    def show
      #TODO, we should obfustate code
      find_subscriber
      render "edit"
    end

    def new
      @subscriber = @campaign.subscribers.new
    end

    def edit
      find_subscriber
    end

    def update
      find_subscriber
      if @subscriber.update_attributes(resource_params) && @subscriber.errors.blank?
        flash[:notice] = "you did it!"
        @subscription.subscribe! unless @subscription.subscribed?
        redirect_to campaign_path(@campaign)
      else
        render "edit"
      end
    end

    def create
      @subscriber = @campaign.list.create_subscriber(resource_params)
      if @subscriber.errors.blank?
        @subscription = @campaign.subscriptions.find_by(subscriber: @subscriber)
        @subscription.subscribe! unless @subscription.subscribed?
        flash[:notice] = "you did it!"
        redirect_to campaign_path(@campaign)
      else
        render "new"
      end
    end

    def delete
      find_subscriber
    end

    def destroy
      find_subscriber
      begin
        if @subscription.unsubscribe!
          flash[:notice] = "Thanks, you will not receive more emails from this newsletter!"
          redirect_to campaign_path(@campaign)
        end
      rescue
        flash[:notice] = "Thanks, you will not receive more emails from this newsletter!"
        redirect_to campaign_path(@campaign)
      end
    end


  protected

    def find_subscriber
      @subscriber = @campaign.list.subscribers.find_by(email: URLcrypt.decode(params[:id]))
      @subscription = @campaign.subscriptions.find_by(subscriber: @subscriber)
    end

    def find_base_models
      @campaign = Chaskiq::Campaign.find(params[:campaign_id])
      @list = @campaign.list
    end


    def resource_params
      return [] if request.get?
      params.require(:subscriber).permit(:email, :name, :last_name)
    end

  end
end

app/controllers/chaskiq/tracks_controller.rb
require_dependency "chaskiq/application_controller"

module Chaskiq
  class TracksController < ApplicationController

    before_action :find_campaign

    #http://localhost:3000/chaskiq/campaigns/1/tracks/1/[click|open|bounce|spam].gif
    %w[open bounce spam].each do |action|
      define_method(action) do
        find_subscriber
        @subscriber.send("track_#{action}".to_sym, { host: get_referrer, campaign_id: @campaign.id })
        #return image
        img_path = Chaskiq::Engine.root.join("app/assets/images/chaskiq", "track.gif")
        send_data File.read(img_path, :mode => "rb"), :filename => '1x1.gif', :type => 'image/gif'
        #send_data File.read(view_context.image_url("chaskiq/track.gif"), :mode => "rb"), :filename => '1x1.gif', :type => 'image/gif'
      end
    end

    def click
      find_subscriber
      #TODO: if subscriber has not an open , we will track open too!
      #that's probably due to plain email or image not beign displayed
      @subscriber.track_click({ host: get_referrer, campaign_id: @campaign.id, data: params[:r] })
      redirect_to params[:r]
    end

  private

    def find_campaign
      @campaign = Chaskiq::Campaign.find(params[:campaign_id])
    end

    def find_subscriber
      @subscriber = @campaign.subscribers.find_by(email: URLcrypt.decode(params[:id]))
    end

  end
end

app/helpers/chaskiq/application_helper.rb
module Chaskiq
  module ApplicationHelper

    def paginate objects, options = {}
      options.reverse_merge!( theme: 'twitter-bootstrap-3' )
      super( objects, options )
    end

    def bootstrap_class_for flash_type
      { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
    end

    def flash_messages(opts = {})

      flash.each do |msg_type, message|
        flash.delete(msg_type)
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}") do 
          concat content_tag(:button, "<i class='fa fa-times-circle'></i>".html_safe, class: "close", data: { dismiss: 'alert' })
          concat message 
        end)
      end

      session.delete(:flash)
      nil
    end
    
  end

end

app/helpers/chaskiq/campaigns_helper.rb
module Chaskiq
  module CampaignsHelper

  end
end

app/helpers/chaskiq/dashboard_helper.rb
module Chaskiq
  module DashboardHelper
  end
end

app/views/layouts/chaskiq/_footer.haml
%footer.footer
  .container
    .row.align-items-center.flex-row-reverse
      .col-auto.ml-lg-auto
        .row.align-items-center
          .col-auto
            %ul.list-inline.list-inline-dots.mb-0
              %li.list-inline-item
                %a{:href => "#"}
                  Documentation
          .col-auto
            %a.btn.btn-outline-primary.btn-sm{:href => "https://github.com/michelson/chaskiq"} Source code
      .col-12.col-lg-auto.mt-3.mt-lg-0.text-center
        with
        %i.fa.fa-heart
        by
        = succeed "." do
          %a{:href => "."} Chaskiq
        %a{:href => "https://codecalm.net", :target => "_blank"} codecalm.net

app/views/layouts/chaskiq/_header.erb
<div class="header py-4">
  <div class="container">
    <div class="d-flex">

      <a class="header-brand" href="<%= root_url %>">
        Chaskiq
        <!--<img src="./demo/brand/tabler.svg" class="header-brand-img" alt="tabler logo">-->
      </a>

      <div class="d-flex order-lg-2 ml-auto">
        
        <% if controller.current_user.present? && Chaskiq::Config.is_admin?(controller.current_user) %>
          <div class="dropdown">
            <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
              <span class="avatar" style="background-image: url('')"></span>
              <span class="ml-2 d-none d-lg-block">
                <span class="text-default">
                  <%= controller.current_user.email %>
                </span>
                
                  <small class="text-muted d-block mt-1">Administrator</small>
             
              </span>
            </a>

            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                <a class="dropdown-item" href="#">
                  <i class="dropdown-icon fe fe-log-out"></i>
                  Sign out
                </a>
            </div>
          </div>
        <% end %>

      </div>

      <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
        <span class="header-toggler-icon"></span>
      </a>
    </div>
  </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg order-lg-first">

        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
          
 
            <li class="nav-item">
              <a class="nav-link" href="<%= manage_campaigns_path %>">
                <i class="fas fa-newspaper"></i>
                Campaigns
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="<%= manage_lists_path %>">
                <i class="fas fa-address-card"></i>
                Lists
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="<%= manage_templates_path %>">
                <i class="fas fa-object-group"></i>
                Templates
              </a>
            </li>

            <li class="separator"></li>
            
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/chaskiq/_navigation.html.haml
%nav.navbar-default{:role => "navigation"}
  .sidebar-collapse
    %ul#side-menu.nav
      %li.nav-header
        .dropdown.profile-element
          %span
            -#%img.img-circle{:alt => "image", :src => image_url( 'profile_small.jpg')}/
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %span.clear
              %span.block.m-t-xs
                %strong.font-bold Chaskiq
              %span.text-muted.text-xs.block
                Admin
                %b.caret
          %ul.dropdown-menu.animated.fadeInRight.m-t-xs
            %li
              %a{:href => ""} Main Settings
            %li.divider
            %li
              %a{:href => ""} Logout
        .logo-element
          CHASKIQ
      %li
        %a{:href => "/"}
          %i.fa.fa-home
          %span.nav-label Home
      %li
        %a{:href => ""}
          %i.fa.fa-bullhorn
          %span.nav-label Campaigns
          %span.fa.arrow
        %ul{:class => "nav nav-second-level"}
          %li= link_to "View all campaigns", manage_campaigns_path
          %li= link_to "New campaigns", new_manage_campaign_path
      %li
        %a{:href => ""}
          %i.fa.fa-list-ol
          %span.nav-label Lists
          %span.fa.arrow
        %ul{:class => "nav nav-second-level"}
          %li= link_to "View all lists", manage_lists_path
          %li= link_to "Create new list", new_manage_list_path
      %li
        %a{:href => ""}
          %i.fa.fa-newspaper-o
          %span.nav-label Templates
          %span.fa.arrow

        %ul{:class => "nav nav-second-level"}
          %li= link_to "All templates", manage_templates_path
          %li= link_to "Create new template", new_manage_template_path

app/views/layouts/chaskiq/_topnavbar.html.haml
.header.py-4
  .container
    .d-flex
      %a.header-brand{:href => root_url}
        Chaskiq
        / <img src="./demo/brand/tabler.svg" class="header-brand-img" alt="tabler logo">
      .d-flex.order-lg-2.ml-auto
        .dropdown
          %a.nav-link.pr-0.leading-none{"data-toggle" => "dropdown", :href => "#"}
            %span.avatar{:style => "background-image: url('')"}
            %span.ml-2.d-none.d-lg-block
              %span.text-default
                = current_user.email
                %small.text-muted.d-block.mt-1 Administrator
          .dropdown-menu.dropdown-menu-right.dropdown-menu-arrow
            /
              <a class="dropdown-item" href="#">
              <i class="dropdown-icon fe fe-user"></i> Profile
              </a>
              <div class="dropdown-divider"></div>
            %a.dropdown-item{:href => ""}
              %i.dropdown-icon.fe.fe-log-out
              = I18n.t("terms_app.sign_out")
      %a.header-toggler.d-lg-none.ml-3.ml-lg-0{"data-target" => "#headerMenuCollapse", "data-toggle" => "collapse", :href => "#"}
        %span.header-toggler-icon

        #headerMenuCollapse.header.collapse.d-lg-flex.p-0
          .container
            .row.align-items-center
              .col-lg.order-lg-first
                %ul.nav.nav-tabs.border-0.flex-column.flex-lg-row

                  %li.nav-item
                    = link_to "Campaigns", manage_campaigns_path, class: "nav-link"
                  %li.nav-item
                    = link_to "Lists", manage_lists_path, class: "nav-link"
                  %li.nav-item
                    = link_to "Templates", manage_templates_path, class: "nav-link"



%header.navbar.navbar-default.navbar-fixed-top{:role => "banner"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} CHASKIQ
    %nav.collapse.navbar-collapse{:role => "navigation"}
      %ul.nav.navbar-nav
        %li
          = link_to "Campaigns", manage_campaigns_path, class: "nav-link"
        %li
          = link_to "Lists", manage_lists_path, class: "nav-link"
        %li
          = link_to "Templates", manage_templates_path, class: "nav-link"

      %ul.nav.navbar-right.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.glyphicon.glyphicon-search
          %ul.dropdown-menu
            %li
              %a{href: ""}
                %i.fa.fa-sign-out
                Log out

app/views/layouts/chaskiq/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= I18n.t("terms_app.title") %></title>

  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">


  <% javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= stylesheet_link_tag    "chaskiq/application", media: "all" %>
  <%= javascript_include_tag "chaskiq/application", debug: true %>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>

<body>

    <div class="page">
      <div class="page-main">
        <%= render 'layouts/chaskiq/header' %>
      
        <div class="my-3 my-md-5">
          <div class="container">
            <p id="notice">
              <%= flash_messages %>
            </p>
            <%= yield %>  
            <%= yield :javascript %>
            <%= yield :charts_js %>
          </div>
        </div>
      </div>

      <%= render partial: "layouts/chaskiq/footer" %>
    </div>
 

</body>
</html>